### ISSUE TITLE
Add Flashcard from image

### ISSUE THREAD

**Issue by Sahilgat** [AY1920S1-CS2103T-W13-3/main#110]

**Comment by Sahilgat** [comment]
Reassigned to me and pushed to 1.3 (partially implemented for now on local copy) since Jun Ren taking over GUI.

**Comment by Sahilgat** [comment]
Feature reallocated as a good-to-have and pushed back to v1.4. Assigned back to Jun Ren

**Comment by chanjunren** [comment]
Decided not to implement
