### ISSUE TITLE
@ckb055 please use the latest version of CATcher

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-W13-3/main#381]
@ckb055 please use the latest version of the CATcher. Your use of an older version is messing up your bug reports.

**Comment by ckb055** [comment]
@damithc sorry, I accidentally submitted ID 1983 using the PE's version of catcher.
I am now using 3.1.11. I used the blue X and then I re-marked it as responded.
Please let me know if it's working now.

**Comment by damithc** [comment]
👍
